apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "{{ .Values.service.isInternal }}"
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "{{ .Values.service.healthPath }}"
      service.beta.kubernetes.io/port_80_health-probe_protocol: "{{ .Values.service.healthProtocol }}"
      service.beta.kubernetes.io/port_80_health-probe_port: "{{ .Values.service.healthPort }}"
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
