replicaCount: 1

producer:
  image: "docker.io/halilkaradayi1936/producer:latest"
  kafkaBrokers: "kafka-service:9092"
  kafkaClientId: "producer-app"
  kafkaTopic: "events"

consumer:
  image: "docker.io/halilkaradayi1936/consumer:latest"
  kafkaBrokers: "kafka-service:9092"
  kafkaClientId: "consumer-app"
  kafkaGroupId: "consumer-group"
  kafkaTopic: "events"
  mongoUri: "mongodb-service:27017"
  mongoDbName: "eventsdb"
  mongoCollection: "events"

restApi:
  image: "docker.io/halilkaradayi1936/api:latest"
  port: 3000
  mongoUri: "mongodb-service:27017"
  mongoDbName: "eventsdb"
  mongoCollection: "events"
