name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag halilkaradayi1936/event-driven:${{ github.sha }}
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image
      run: docker push halilkaradayi1936/event-driven:${{ github.sha }}     

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
    - name: Set up Helm
      uses: azure/setup-helm@v1
    - name: Set up kubeconfig
      shell: bash
      env:
        KUBECONFIG_ENCODED: ${{ secrets.KUBECONFIG }}
      run: |
        mkdir -p $HOME/.kube
        echo "${KUBECONFIG_ENCODED}" | base64 --decode > $HOME/.kube/config
        kubectl cluster-info
     
    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install event-driven ./web \
        --namespace event-driven \
        --set image.repository=docker.io/halilkaradayi1936/event-driven \
        --set image.tag=${{ github.sha }}