# Default values for tea.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dockerhub.io/halilkaradayi1936/event-driven:27eb77be7baebe5571a5e666704b0572a428611f
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  - name: github-registry
nameOverride: ""
fullnameOverride: ""

secrets:
  data:
    NEXT_PUBLIC_OLEY_TJK_URL: "https://api.tjk.loodos.dev/api/v1"
    NEXT_PUBLIC_CLIENT_ID: "enliq_backoffice_client"
    NEXT_PUBLIC_CLIENT_SECRET:  "388D45FA-B36B-4988-BA59-B187D329C299"
    NEXT_PUBLIC_CDN_URL: "https://cdn.enliq.com"
    
envs:
- NEXT_PUBLIC_OLEY_TJK_URL
- NEXT_PUBLIC_CLIENT_ID
- NEXT_PUBLIC_CLIENT_SECRET
- NEXT_PUBLIC_CDN_URL

matchNames:
 - $NAMESPACES

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

#securityContext:
#  capabilities:
#    add:
#    - SYS_PTRACE

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
     cpu: 200m
     memory: 256Mi
  requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
